name: Test CI

on: [pull_request_target]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build and test with Maven
      run: ls -lah
    - name: Build and test with Maven
      run: echo "${{ secrets.A_SECRET }}"