name: Test CI

on: [push]

jobs:
  ui_tests:
    strategy:
      # fail-fast: false
      matrix:
        browser: ['chrome', 'edge']
        machines: [1, 2, 3]
    steps:
      - name: ECHO
        run: echo I am running on machine "${{ matrix.machine }}, for browser {{ matrix.browser }}"
